// Generated by CoffeeScript 1.7.1
var path;

path = require('path');

module.exports = function(collection, file, dir, value) {
  var chunks, cursor, i, _i, _ref, _results;
  chunks = path.relative(dir, file.replace(/\.[^.]+$/, '')).split(path.sep);
  cursor = collection;
  _results = [];
  for (i = _i = 0, _ref = chunks.length - 1; _i <= _ref; i = _i += 1) {
    if (i < chunks.length - 1) {
      if (cursor[chunks[i]] == null) {
        _results.push(cursor = cursor[chunks[i]] = {});
      } else {
        _results.push(cursor = cursor[chunks[i]]);
      }
    } else {
      _results.push(cursor[chunks[i]] = value);
    }
  }
  return _results;
};
