// Generated by CoffeeScript 1.7.1
module.exports.project = require('./project');

module.exports.plugin = require('./plugin');

module.exports.server = function(projectdir, appdir, appext, config, mean) {
  return require('./server')(projectdir, appdir, appext, config, mean);
};
