// Generated by CoffeeScript 1.7.1
var dependable, events, express, fs, glob, mongoose, path, postrender, swig, utils, _,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

express = require('express');

mongoose = require('mongoose');

dependable = require('dependable');

postrender = require('express-postrender');

swig = require('swig');

path = require('path');

glob = require('glob');

events = require('events');

fs = require('fs');

_ = require('lodash');

utils = require('./utils');

module.exports = function(projectDir, appDir, ext) {
  var app, assetFile, assets, chainware, config, dir, init, injector, injectors, load, loaded, name, pkg, publicDir, relativeAppDir, relativeProjectDir, route, routed, router, __injectors, __routes;
  relativeProjectDir = path.relative(__dirname, projectDir);
  relativeAppDir = path.relative(__dirname, appDir);
  if (process.env.NODE_ENV == null) {
    process.env.NODE_ENV = 'development';
  }
  pkg = require(path.join(projectDir, 'package.json'));
  name = pkg.name;
  publicDir = path.join(projectDir, "public/" + name);
  dir = {
    project: projectDir,
    "public": publicDir,
    plugins: "" + projectDir + "/plugins",
    vhosts: "" + projectDir + "/vhosts",
    app: appDir
  };
  if (fs.existsSync("" + appDir + "/chainware" + ext)) {
    chainware = require("" + relativeAppDir + "/chainware");
  }
  injector = dependable.container();
  injector.register('$injector', injector);
  injector.register('$env', process.env.NODE_ENV);
  injector.register('$dir', dir);
  injector.register('$ext', ext);
  injector.register('$name', name);
  injector.register('$assets', {
    js: {},
    css: {},
    other: {}
  });
  injector.register('$mounts', ['/']);
  injector.register('$mount', '/', injector.register('$plugin', function() {
    return function(mounts, plugin, shared) {
      var a, assets, injectors, k, pluginAssets, r, v, __injectors, __routes, _i, _j, _len, _len1, _ref, _ref1, _ref2;
      if (plugin == null) {
        plugin = mounts;
        mounts = [];
      }
      if (fs.existsSync("" + plugin + ext)) {
        plugin = require("" + plugin + ext);
      } else {
        plugin = require("" + plugin + ".js");
      }
      if ((shared == null) || shared === true) {
        plugin.injector.register('__shared', true);
        plugin.injector.register('$connection', function() {
          return injector.get('$connection');
        });
        plugin.injector.register('$mongoose', function() {
          return injector.get('$mongoose');
        });
      }
      if (_.isString(mounts)) {
        mounts = [mounts];
      }
      plugin.injector.register('$mounts', mounts);
      assets = injector.get('$assets');
      pluginAssets = plugin.injector.get('$assets');
      if (pluginAssets[name] == null) {
        pluginAssets[name] = assets;
      }
      plugin.injector.register('$assets', pluginAssets);
      plugin.load();
      injectors = injector.get('$injectors');
      _ref = plugin.injector.get('$injectors');
      for (k in _ref) {
        v = _ref[k];
        if (injectors[k] == null) {
          injectors[k] = v;
        }
        if ((assets[k] == null) && k !== name) {
          a = v.get('$assets');
          if (a[name] != null) {
            delete a[name];
          }
          assets[k] = a;
        }
      }
      __injectors = injector.get('__injectors');
      _ref1 = plugin.injector.get('__injectors');
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        v = _ref1[_i];
        if (__indexOf.call(__injectors, v) < 0) {
          __injectors.push(v);
        }
      }
      if (mounts.length > 0) {
        __routes = injector.get('__routes');
        _ref2 = plugin.injector.get('__routes');
        for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
          r = _ref2[_j];
          if (__indexOf.call(__routes, r) < 0) {
            __routes.push(r);
          }
        }
        injector.register('__routes', __routes);
      }
    };
  }));
  injector.register('$express', function() {
    return express;
  });
  injector.register('$dependable', function() {
    return dependable;
  });
  injector.register('$glob', function() {
    return glob;
  });
  injector.register('$lodash', function() {
    return _;
  });
  injectors = {};
  injectors[name] = injector;
  injector.register('$injectors', injectors);
  __injectors = [injector];
  injector.register('__injectors', __injectors);
  __routes = [];
  injector.register('__routes', __routes);
  injector.register('__shared', false);
  config = {};
  config.database = {};
  config.database.uri = 'mongodb://localhost/meanstackjs';
  config.database.options = {};
  config.secret = 'meanstackjs';
  config.mount = '/';
  config.port = 3000;
  config.router = {
    caseSensitive: false,
    strict: false
  };
  config.assets = {};
  config.assets.expiry = 0;
  if (process.env.NODE_ENV === 'production') {
    config.assets.expiry = 1000 * 3600 * 24 * 365;
  }
  config.middleware = {};
  config.middleware['vhosted'] = true;
  config.middleware['compression'] = {
    level: 9
  };
  config.middleware['cookie-parser'] = true;
  config.middleware['body-parser'] = true;
  config.middleware['express-validator'] = true;
  config.middleware['method-override'] = true;
  config.middleware['express-session'] = {
    key: 'sid'
  };
  config.middleware['connect-mongo'] = true;
  config.middleware['view-helpers'] = true;
  config.middleware['connect-flash'] = true;
  config.middleware['serve-favicon'] = false;
  config.middleware['errorhandler'] = true;
  if (process.env.NODE_ENV === 'production') {
    config.middleware['errorhandler'] = false;
  }
  config.views = {};
  config.views.dir = path.resolve("" + appDir + "/");
  if (process.env.NODE_ENV === 'production') {
    config.views.cache = true;
  } else {
    config.views.cache = false;
  }
  config.views.callback = function(html) {
    return html;
  };
  config.views.extension = 'html';
  injector.register('$config', config);
  if ((chainware != null ? chainware.config : void 0) != null) {
    injector.resolve(chainware.config);
  }
  if (config.mount[config.mount.length - 1] !== '/') {
    config.mount += '/';
  }
  assetFile = path.join(publicDir, 'assets.json');
  if (fs.existsSync(assetFile)) {
    assets = JSON.parse(fs.readFileSync(assetFile));
    injector.register('$assets', assets);
  }
  app = express();
  injector.register('$app', function() {
    return app;
  });
  assets = injector.get('$assets');
  app.locals.assets = assets;
  app.locals.mount = config.mount;
  app.locals.name = name;
  router = express.Router(config.router);
  injector.register('$router', function() {
    return router;
  });
  injector.register('$route', function() {
    return express.Router(config.router);
  });
  if ((chainware != null ? chainware.dependencies : void 0) != null) {
    injector.resolve(chainware.dependencies);
  }
  routed = false;
  route = function() {
    if (routed) {
      return;
    }
    routed = true;
    if ((chainware != null ? chainware.routes : void 0) != null) {
      return injector.resolve(chainware.routes);
    }
  };
  loaded = false;
  load = function() {
    var connected, connection, emitter, engine, globDir, i, k, resolve, v, views, __shared;
    if (loaded) {
      return;
    }
    loaded = true;
    __shared = injector.get('__shared');
    __routes = injector.get('__routes');
    __routes.push(route);
    if ((chainware != null ? chainware.beforeLoad : void 0) != null) {
      injector.resolve(chainware.beforeLoad);
    }
    if (config.middleware['cookie-parser']) {
      config.middleware['cookie-parser'] = config.secret;
    }
    if (config.middleware['express-session']) {
      config.middleware['express-session']['secret'] = config.secret;
    }
    emitter = new events.EventEmitter();
    injector.register('$emitter', function() {
      return emitter;
    });
    if (!__shared) {
      connected = function() {
        return emitter.emit('mongoose-connected');
      };
      if (_.size(config.database.options) > 0) {
        connection = mongoose.createConnection(config.database.uri, config.database.options, connected);
      } else {
        connection = mongoose.createConnection(config.database.uri, connected);
      }
      injector.register('$connection', function() {
        return connection;
      });
      injector.register('$mongoose', function() {
        return mongoose;
      });
    }
    if (chainware != null ? chainware.plugins : void 0) {
      injector.resolve(chainware.plugins);
    }
    __injectors.push(__injectors.shift());
    if (config.views.render == null) {
      if (config.views.cache) {
        engine = new swig.Swig({
          loader: swig.loaders.fs(config.views.dir),
          cache: 'memory'
        });
        app.locals.cache = 'memory';
      } else {
        engine = new swig.Swig({
          loader: swig.loaders.fs(config.views.dir),
          cache: false
        });
        app.locals.cache = false;
      }
      config.views.render = engine.renderFile;
    }
    app.set('view cache', config.views.cache);
    app.set('views', config.views.dir);
    views = {};
    config.views = postrender(config.views, config.views.callback, 'render');
    app.set('view engine', config.views.extension);
    app.engine(config.views.extension, config.views.render);
    globDir = path.resolve("" + config.views.dir + "/**/*." + config.views.extension);
    glob(globDir, {
      sync: true
    }, function(err, files) {
      var file, renderer, _i, _len, _results;
      if (err) {
        console.log(err);
        process.exit(0);
      }
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        renderer = new utils.Renderer(file, config.views.render, config.views.cache, app.locals);
        _results.push(utils.aggregate(views, file, config.views.dir, renderer));
      }
      return _results;
    });
    for (k in injectors) {
      v = injectors[k];
      if (k !== name) {
        views[k] = v.get('$views');
      }
    }
    injector.register('$views', views);
    resolve = function(prop, key) {
      var args, construct, create, filter, get, i, match, overrides, r, singleton, wrap;
      filter = function(instance) {
        return instance;
      };
      wrap = function(instance) {
        return function() {
          return instance;
        };
      };
      get = function(instance) {
        return function() {
          var r;
          for (k in injectors) {
            v = injectors[k];
            if (instance.substring(0, k.length).replace('.', '-') === k) {
              r = instance.substring(k.length + 1);
              if (r.length > 0) {
                return v.get(r);
              }
            }
          }
          return injector.get(instance);
        };
      };
      construct = function(key, instance, args) {
        return function() {
          injector.register(key, construct(key, instance, args));
          return instance.construct(args);
        };
      };
      create = function(key, instance, args) {
        return function() {
          injector.register(key, create(key, instance, args));
          return injector.get(instance, args);
        };
      };
      if (prop.singleton != null) {
        singleton = prop.singleton;
      } else {
        singleton = true;
      }
      if (_.isFunction(prop)) {
        if ((prop.inject != null) || prop.name.length > 0) {
          overrides = {};
          match = prop.toString().match(/function.*?\(([\s\S]*?)\)/);
          if (match == null) {
            throw new Error("could not parse function arguments: " + (prop != null ? prop.toString() : void 0));
          }
          args = match[1].split(",").filter(filter).map(function(str) {
            return str.trim();
          });
          if (prop.inject == null) {
            prop.inject = args;
          }
          if (prop.name.length > 0) {
            prop.construct = function(a) {
              var fconstructor, nconstructor;
              fconstructor = prop;
              nconstructor = function() {
                return fconstructor.apply(this, a);
              };
              nconstructor.prototype = fconstructor.prototype;
              return new nconstructor();
            };
          }
          for (i in args) {
            r = args[i];
            overrides[r] = get(prop.inject[i]);
          }
        }
      }
      if (prop.inject != null) {
        if (prop.name.length > 0) {
          injector.register("__" + key, wrap(prop));
        } else {
          injector.register("__" + key, prop);
        }
        return injector.register(key, function() {
          var e, l, res;
          if (prop.name.length > 0) {
            args = [];
            for (l in overrides) {
              e = overrides[l];
              args.push(e());
            }
            if (singleton) {
              res = injector.get("__" + key).construct(args);
              injector.register(key, wrap(res));
            } else {
              res = construct(key, injector.get("__" + key), args)();
            }
          } else {
            for (l in overrides) {
              e = overrides[l];
              overrides[l] = e();
            }
            if (singleton) {
              res = injector.get("__" + key, overrides);
              injector.register(key, wrap(res));
            } else {
              res = create(key, "__" + key, overrides)();
            }
          }
          return res;
        });
      } else {
        if (singleton) {
          return injector.register(key, prop);
        } else {
          injector.register("__" + key, prop);
          return injector.register(key, function() {
            return create(key, "__" + key, {})();
          });
        }
      }
    };
    dir = path.resolve(appDir);
    glob("" + dir + "/**/*" + ext, {
      sync: true
    }, function(err, files) {
      var excluded, file, mdl, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        excluded = path.relative(dir, file);
        if (excluded === ("bootstrap" + ext) || excluded === ("chainware" + ext)) {
          continue;
        }
        mdl = require(file);
        _results.push(_.forOwn(mdl, function(prop, key) {
          if (prop.namespace != null) {
            key = "" + prop.namespace + "." + key;
          }
          return resolve(prop, key);
        }));
      }
      return _results;
    });
    for (k in injectors) {
      v = injectors[k];
      if (k !== name) {
        i = v.get('$injectors');
        i[name] = injector;
      }
    }
    if ((chainware != null ? chainware.afterLoad : void 0) != null) {
      return injector.resolve(chainware.afterLoad);
    }
  };
  init = function() {
    var cm, connection, es, k, m, mount, r, store, v, _i, _j, _k, _len, _len1, _len2, _ref;
    load();
    connection = injector.get('$connection');
    if ((chainware != null ? chainware.beforeInit : void 0) != null) {
      injector.resolve(chainware.beforeInit);
    }
    if ((pkg.dependencies['connect-mongo'] != null) && (pkg.dependencies['express-session'] != null)) {
      if (config.middleware['express-session'] && config.middleware['connect-mongo']) {
        if (_.isBoolean(config.middleware['connect-mongo'])) {
          config.middleware['connect-mongo'] = {};
        }
        config.middleware['connect-mongo']['db'] = connection.db;
        cm = require("" + relativeProjectDir + "/node_modules/connect-mongo");
        es = require("" + relativeProjectDir + "/node_modules/express-session");
        store = new (cm(es))(config.middleware['connect-mongo']);
        if (_.isBoolean(config.middleware['express-session'])) {
          config.middleware['express-session'] = {};
        }
        config.middleware['express-session']['store'] = store;
      }
    }
    if (config.router.strict) {
      app.enable('strict routing');
    }
    if (config.router.caseSensitive) {
      app.enable('case sensitive routing');
    }
    if ((chainware != null ? chainware.beforeMiddleware : void 0) != null) {
      injector.resolve(chainware.beforeMiddleware);
    }
    app.use(function(req, res, next) {
      res.removeHeader('X-Powered-By');
      return next();
    });
    if (pkg.dependencies['compression'] != null) {
      if ((chainware != null ? chainware.beforeCompression : void 0) != null) {
        injector.resolve(chainware.beforeCompression);
      }
      if (config.middleware['compression']) {
        m = require("" + relativeProjectDir + "/node_modules/compression");
        if (!_.isBoolean(config.middleware['compression'])) {
          app.use(m(config.middleware['compression']));
        } else {
          app.use(m());
        }
      }
      if ((chainware != null ? chainware.afterCompression : void 0) != null) {
        injector.resolve(chainware.afterCompression);
      }
    }
    if (pkg.dependencies['serve-favicon'] != null) {
      if ((chainware != null ? chainware.beforeServeFavicon : void 0) != null) {
        injector.resolve(chainware.beforeServeFavicon);
      }
      if (config.middleware['serve-favicon']) {
        m = require("" + relativeProjectDir + "/node_modules/serve-favicon");
        if (!_.isBoolean(config.middleware['serve-favicon'])) {
          app.use(m("" + publicDir + "/favicon.ico", config.middleware['serve-favicon']));
        } else {
          app.use(m("" + publicDir + "/favicon.ico"));
        }
      }
      if ((chainware != null ? chainware.afterServeFavicon : void 0) != null) {
        injector.resolve(chainware.afterServeFavicon);
      }
    }
    if ((chainware != null ? chainware.beforeStatic : void 0) != null) {
      injector.resolve(chainware.beforeStatic);
    }
    for (k in injectors) {
      v = injectors[k];
      dir = v.get('$dir');
      name = v.get('$name');
      app.use("/public/" + name, express["static"](path.join(dir.project, "public/" + name), {
        maxAge: config.assets.expiry
      }));
    }
    if ((chainware != null ? chainware.afterStatic : void 0) != null) {
      injector.resolve(chainware.afterStatic);
    }
    if (pkg.dependencies['cookie-parser'] != null) {
      if ((chainware != null ? chainware.beforeCookieParser : void 0) != null) {
        injector.resolve(chainware.beforeCookieParser);
      }
      if (config.middleware['cookie-parser']) {
        m = require("" + relativeProjectDir + "/node_modules/cookie-parser");
        if (!_.isBoolean(config.middleware['cookie-parser'])) {
          app.use(m(config.middleware['cookie-parser']));
        } else {
          app.use(m());
        }
      }
      if ((chainware != null ? chainware.afterCookieParser : void 0) != null) {
        injector.resolve(chainware.afterCookieParser);
      }
    }
    if (pkg.dependencies['body-parser'] != null) {
      if ((chainware != null ? chainware.beforeBodyParser : void 0) != null) {
        injector.resolve(chainware.beforeBodyParser);
      }
      if (config.middleware['body-parser']) {
        m = require("" + relativeProjectDir + "/node_modules/body-parser");
        app.use(m());
      }
      if ((chainware != null ? chainware.afterBodyParser : void 0) != null) {
        injector.resolve(chainware.afterBodyParser);
      }
    }
    if (pkg.dependencies['express-validator'] != null) {
      if ((chainware != null ? chainware.beforeExpressValidator : void 0) != null) {
        injector.resolve(chainware.beforeExpressValidator);
      }
      if (config.middleware['express-validator']) {
        m = require("" + relativeProjectDir + "/node_modules/express-validator");
        if (!_.isBoolean(config.middleware['express-validator'])) {
          app.use(m(config.middleware['express-validator']));
        } else {
          app.use(m());
        }
      }
      if ((chainware != null ? chainware.afterExpressValidator : void 0) != null) {
        injector.resolve(chainware.afterExpressValidator);
      }
    }
    if (pkg.dependencies['method-override'] != null) {
      if ((chainware != null ? chainware.beforeMethodOverride : void 0) != null) {
        injector.resolve(chainware.beforeMethodOverride);
      }
      if (config.middleware['method-override']) {
        m = require("" + relativeProjectDir + "/node_modules/method-override");
        app.use(m());
      }
      if ((chainware != null ? chainware.afterMethodOverride : void 0) != null) {
        injector.resolve(chainware.afterMethodOverride);
      }
    }
    if (pkg.dependencies['express-session'] != null) {
      if ((chainware != null ? chainware.beforeExpressSession : void 0) != null) {
        injector.resolve(chainware.beforeExpressSession);
      }
      if (config.middleware['express-session']) {
        m = require("" + relativeProjectDir + "/node_modules/express-session");
        if (!_.isBoolean(config.middleware['express-session'])) {
          app.use(m(config.middleware['express-session']));
        } else {
          app.use(m());
        }
      }
      if ((chainware != null ? chainware.afterExpressSession : void 0) != null) {
        injector.resolve(chainware.afterExpressSession);
      }
    }
    if (pkg.dependencies['view-helpers'] != null) {
      if ((chainware != null ? chainware.beforeViewHelpers : void 0) != null) {
        injector.resolve(chainware.beforeViewHelpers);
      }
      if (config.middleware['view-helpers']) {
        m = require("" + relativeProjectDir + "/node_modules/view-helpers");
        app.use(m(name));
      }
      if ((chainware != null ? chainware.afterViewHelpers : void 0) != null) {
        injector.resolve(chainware.afterViewHelpers);
      }
    }
    if (pkg.dependencies['connect-flash'] != null) {
      if ((chainware != null ? chainware.beforeConnectFlash : void 0) != null) {
        injector.resolve(chainware.beforeConnectFlash);
      }
      if (config.middleware['connect-flash']) {
        m = require("" + relativeProjectDir + "/node_modules/connect-flash");
        app.use(m());
      }
      if ((chainware != null ? chainware.afterConnectFlash : void 0) != null) {
        injector.resolve(chainware.afterConnectFlash);
      }
    }
    if ((chainware != null ? chainware.beforeRouting : void 0) != null) {
      injector.resolve(chainware.beforeRouting);
    }
    __routes = injector.get('__routes');
    for (_i = 0, _len = __routes.length; _i < _len; _i++) {
      r = __routes[_i];
      r();
    }
    __injectors = injector.get('__injectors');
    for (_j = 0, _len1 = __injectors.length; _j < _len1; _j++) {
      v = __injectors[_j];
      _ref = v.get('$mounts');
      for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
        mount = _ref[_k];
        app.use(mount, v.get('$router'));
      }
    }
    if ((chainware != null ? chainware.afterRouting : void 0) != null) {
      injector.resolve(chainware.afterRouting);
    }
    if ((chainware != null ? chainware.afterMiddleware : void 0) != null) {
      injector.resolve(chainware.afterMiddleware);
    }
    if (pkg.dependencies['errorhandler'] != null) {
      if ((chainware != null ? chainware.beforeErrorHandler : void 0) != null) {
        injector.resolve(chainware.beforeErrorHandler);
      }
      if (config.middleware['errorhandler']) {
        m = require("" + relativeProjectDir + "/node_modules/errorhandler");
        app.use(m());
      }
      if ((chainware != null ? chainware.afterErrorHandler : void 0) != null) {
        injector.resolve(chainware.afterErrorHandler);
      }
    }
    if ((chainware != null ? chainware.afterInit : void 0) != null) {
      injector.resolve(chainware.afterInit);
    }
    return injector;
  };
  return {
    injector: injector,
    load: load,
    init: init
  };
};
