// Generated by CoffeeScript 1.7.1
var Renderer, _;

_ = require('lodash');

module.exports = Renderer = (function() {
  function Renderer(filename, renderer, cache, locals) {
    this.filename = filename;
    this.renderer = renderer;
    this.cache = cache;
    this.locals = locals;
    return;
  }

  Renderer.prototype.render = function(req, res, options, fn) {
    var err, opts;
    options = options || {};
    if (_.isFunction(options)) {
      fn = options;
      options = {};
    }
    fn = fn || function(err, str) {
      if (err) {
        return req.next(err);
      }
      res.send(str);
    };
    opts = {};
    opts = _.assign(opts, this.locals);
    opts = _.assign(opts, res.locals);
    opts = _.assign(opts, options);
    opts.cache = opts.cache == null ? this.cache : opts.cache;
    opts.filename = this.filename;
    try {
      this.renderer(this.filename, opts, fn);
    } catch (_error) {
      err = _error;
      fn(err);
    }
  };

  return Renderer;

})();
