// Generated by CoffeeScript 1.7.1
var path;

path = require('path');

module.exports = function(projectdir, appdir, appext, config, mean) {
  var relappdir, relprojectdir, server, vhosted, vhosts;
  relappdir = path.relative(__dirname, appdir);
  relprojectdir = path.relative(__dirname, projectdir);
  if (config.middleware['vhosted']) {
    server = require('express')();
    if (config.router.strict) {
      server.enable('strict routing');
    }
    if (config.router.caseSensitive) {
      server.enable('case sensitive routing');
    }
    vhosted = require('vhosted');
    vhosts = mean.resolve(require("" + relprojectdir + "/vhosts" + appext));
    server = vhosted(server, projectdir, vhosts);
    mean.register('server', function() {
      return server;
    });
  } else {
    mean.register('server', function() {
      return mean.get('app');
    });
  }
  return mean.resolve(require("" + relappdir + "/server"));
};
