// Generated by CoffeeScript 1.7.1
var Renderer, path, _;

path = require('path');

_ = require('lodash');

module.exports.Renderer = Renderer = (function() {
  function Renderer(filename, renderer, cache, locals) {
    this.filename = filename;
    this.renderer = renderer;
    this.cache = cache;
    this.locals = locals;
    return;
  }

  Renderer.prototype.render = function(req, res, options, fn) {
    var err, opts;
    options = options || {};
    if (_.isFunction(options)) {
      fn = options;
      options = {};
    }
    fn = fn || function(err, str) {
      if (err) {
        return req.next(err);
      }
      res.send(str);
    };
    opts = {};
    opts = _.assign(opts, this.locals);
    opts = _.assign(opts, res.locals);
    opts = _.assign(opts, options);
    opts.cache = opts.cache == null ? this.cache : opts.cache;
    opts.filename = this.filename;
    try {
      this.renderer(this.filename, opts, fn);
    } catch (_error) {
      err = _error;
      fn(err);
    }
  };

  return Renderer;

})();

module.exports.aggregate = function(collection, file, dir, value) {
  var chunks, cursor, i, _i, _ref, _results;
  chunks = path.relative(dir, file.replace(/\.[^.]+$/, '')).split(path.sep);
  cursor = collection;
  _results = [];
  for (i = _i = 0, _ref = chunks.length - 1; _i <= _ref; i = _i += 1) {
    if (i < chunks.length - 1) {
      if (collection[chunks[i]] == null) {
        _results.push(cursor = collection[chunks[i]] = {});
      } else {
        _results.push(void 0);
      }
    } else {
      _results.push(cursor[chunks[i]] = value);
    }
  }
  return _results;
};
